apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-http
  name: hello-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-http
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-http
    spec:
      containers:
      - image: httpd:latest
        name: httpd
        resources: {}
status: {}
