apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-world-app
  name: hello-world-app
spec:
  containers:
  - image: stivenza96/dockerapp:hello-world
    name: hello-world-app
    ports:
    - containerPort: 5000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
