apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: nginx:latest
    name: hello
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 50m
        memory: 6Gi
      requests:
        cpu: 50m
        memory: 6Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
