apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-http
  name: hello-http
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-http
  type: LoadBalancer
status:
  loadBalancer: {}
